Add vue header
cc-archive/vue-vocabulary pull request #209
Opened 2020-04-15 15:17 UTC by jahnvigupta

## Fixes

Fixes #193  by @dhruvkb 

## Description

This PR adds the vue version of Header component.
## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-04-16 16:27 UTC, dhruvkb requested changes

2020-04-16 16:27 UTC, dhruvkb commented on src/patterns/Header/Header.vue
> +    </div>
This isn't part of the `Header`. It's just present in the story.

2020-04-16 16:27 UTC, dhruvkb commented on src/patterns/Header/Header.vue
> +      }
Move the `div` and code related to it to the story instead of the component.

2020-04-16 16:27 UTC, dhruvkb commented on src/stories/header.stories.mdx
> +    })}</Story>
Fix code indentation.

2020-04-16 16:27 UTC, dhruvkb commented on src/stories/header.stories.mdx
> +    })}</Story>
Fix indentation.

2020-04-18 03:41 UTC, dhruvkb requested changes
Import assets from Vocabulary, don't recreate them.

2020-05-02 10:24 UTC, dhruvkb requested changes
Some more very minor changes.

2020-05-02 10:24 UTC, dhruvkb commented on src/patterns/Header/Header.vue
> +      <nav class="navbar" :class = size>
Your indentation is still off here. Please use an editor like VS Code or an IDE like WebStorm to avoid issues like this.

2020-05-02 10:24 UTC, dhruvkb commented on src/patterns/Header/Header.vue
> +              preserveAspectRatio="xMidyMid meet"
```suggestion
              preserveAspectRatio="xMidYMid meet"
```
See creativecommons/vocabulary#335.

2020-05-02 10:24 UTC, dhruvkb commented on src/patterns/Header/Header.vue
> +      },
Since size only has two states, we could go with a `Boolean` prop like `isSmall` (or `isBig`, whichever you prefer).

2020-05-03 06:52 UTC, jahnvigupta commented
@dhruvkb I have made the required changes. Please check.

2020-08-26 00:41 UTC, zackkrida commented
Hi @jahnvigupta thank you for this PR but we are going to be making some significant changes to `vue-vocabulary` and will be making the header component work differently. Thank you for your PR, we will let you know when we're ready with the new version if you'd like to work on it.

2020-08-26 00:41 UTC, closed without merging